### ISSUE TITLE
Documentation is failing 

### ISSUE THREAD

**Issue by nilshempelmann** [climateintelligence/hawk#9]
## Description

read the docs compilation is failing due to missing pandas in environment: 

https://readthedocs.org/projects/clint-hawk/builds/24036359/

**Comment by nilshempelmann** [comment]
@PaoloBonettiPolimi I fixed the first issue, but the build is still failing: 

missing module: 'tigramite' 

You can check the build here: 
https://readthedocs.org/projects/clint-hawk/builds/24047513/

**Comment by PaoloBonettiPolimi** [comment]
I should have solved the issue, now the following link contains the updated version of the documentation: https://clint-hawk.readthedocs.io/en/latest/
